export const LOADING_REPOSITORY_LIST = "LOADING_REPOSITORY_LIST";
export const SHOW_REPOSITORY_LIST = "SHOW_REPOSITORY_LIST";
export const LOADING_LANGUAGE_LIST = "LOADING_LANGUAGE_LIST";
export const SHOW_LANGUAGE_LIST = "SHOW_LANGUAGE_LIST";
export const ERROR = "ERROR";
